/**
 * 菜谱数据 - 按中餐/轻食和早/中/晚分类
 * 每个菜谱包含制作方法
 */

export interface Recipe {
  id: string;
  name: string;
  category: 'chinese' | 'light';
  mealType: 'breakfast' | 'lunch' | 'dinner';
  calorie: number;
  protein: number;
  fat: number;
  carbs: number;
  description: string;
  method: string;
  suitableTarget: ('fat' | 'muscle' | 'keep')[];
  difficulty: 'easy' | 'medium' | 'hard';
  cookTime: number;
  image: string;
}

export const RECIPES: Recipe[] = [
  // ========== 中餐 - 早餐 ==========
  {
    id: 'c_b_1',
    name: '小米南瓜粥',
    category: 'chinese',
    mealType: 'breakfast',
    calorie: 95,
    protein: 3,
    fat: 0.5,
    carbs: 20,
    description: '养胃健脾，早餐暖胃首选',
    method: '1.小米100g洗净备用\n2.南瓜200g去皮切块\n3.锅中加水800ml烧开\n4.放入小米煮10分钟\n5.加入南瓜块再煮15分钟\n6.南瓜软烂即可出锅',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 25,
    image: '',
  },
  {
    id: 'c_b_2',
    name: '鲜肉小馄饨',
    category: 'chinese',
    mealType: 'breakfast',
    calorie: 280,
    protein: 12,
    fat: 8,
    carbs: 38,
    description: '皮薄馅嫩，汤鲜味美',
    method: '1.猪肉馅200g加姜末、葱花、盐调味\n2.馄饨皮包馅捏合\n3.锅中烧水，下馄饨煮3分钟\n4.碗底放紫菜、虾皮、香油、盐\n5.连汤盛入碗中即可',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 20,
    image: '',
  },
  {
    id: 'c_b_3',
    name: '葱油拌面',
    category: 'chinese',
    mealType: 'breakfast',
    calorie: 350,
    protein: 8,
    fat: 12,
    carbs: 52,
    description: '香气扑鼻，经典中式早餐',
    method: '1.挂面200g煮熟过凉水\n2.小葱4根切段\n3.锅中多放油，小火炸葱段至焦黄\n4.加生抽2勺、老抽1勺、糖1勺熬汁\n5.面条沥干，浇上葱油汁拌匀',
    suitableTarget: ['keep', 'muscle'],
    difficulty: 'easy',
    cookTime: 15,
    image: '',
  },
  {
    id: 'c_b_4',
    name: '生煎包',
    category: 'chinese',
    mealType: 'breakfast',
    calorie: 320,
    protein: 14,
    fat: 15,
    carbs: 35,
    description: '底脆汁多，鲜肉爆汁',
    method: '1.猪肉馅300g加皮冻、姜末、生抽调味\n2.发面皮包馅，收口朝上\n3.平底锅刷油，排入生煎包\n4.小火煎至底部金黄\n5.加淀粉水没过1/3，盖盖焖10分钟\n6.水干后撒葱花、黑芝麻出锅',
    suitableTarget: ['muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 30,
    image: '',
  },
  {
    id: 'c_b_5',
    name: '豆浆油条',
    category: 'chinese',
    mealType: 'breakfast',
    calorie: 380,
    protein: 10,
    fat: 16,
    carbs: 48,
    description: '国民早餐，经典搭配',
    method: '1.黄豆100g浸泡8小时\n2.豆浆机打浆煮沸\n3.油条粉200g加水揉面醒发\n4.面团成长条切段\n5.两段叠放，筷子中间压一下\n6.油锅180度炸至金黄膨胀',
    suitableTarget: ['muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 25,
    image: '',
  },
  {
    id: 'c_b_6',
    name: '韭菜盒子',
    category: 'chinese',
    mealType: 'breakfast',
    calorie: 260,
    protein: 9,
    fat: 11,
    carbs: 32,
    description: '外酥里嫩，鲜香可口',
    method: '1.韭菜300g切碎，鸡蛋3个炒碎\n2.加粉丝碎、虾皮、盐、香油拌匀\n3.面团擀成圆皮，包入馅料\n4.对折捏紧边缘呈半月形\n5.平底锅少油，小火烙至两面金黄\n6.出锅趁热享用',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 25,
    image: '',
  },
  {
    id: 'c_b_7',
    name: '皮蛋瘦肉粥',
    category: 'chinese',
    mealType: 'breakfast',
    calorie: 180,
    protein: 12,
    fat: 6,
    carbs: 22,
    description: '广式经典，绵滑鲜香',
    method: '1.大米100g洗净，加少许油腌制30分钟\n2.皮蛋2个切丁，瘦肉100g切丝\n3.锅中加水1000ml烧开，下米煮30分钟\n4.米粥粘稠后加皮蛋和肉丝\n5.煮5分钟至肉熟透\n6.加盐、白胡椒粉、葱花调味',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 40,
    image: '',
  },
  {
    id: 'c_b_8',
    name: '肠粉',
    category: 'chinese',
    mealType: 'breakfast',
    calorie: 200,
    protein: 8,
    fat: 5,
    carbs: 32,
    description: '广式早茶，嫩滑爽弹',
    method: '1.粘米粉200g加水调成米浆\n2.蒸盘刷油，倒入薄薄一层米浆\n3.可加蛋液、肉末、虾仁\n4.大火蒸2-3分钟至透明\n5.刮下卷起装盘\n6.淋上酱油、熟油即可',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 15,
    image: '',
  },

  // ========== 中餐 - 午餐 ==========
  {
    id: 'c_l_1',
    name: '红烧鸡块',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 280,
    protein: 28,
    fat: 14,
    carbs: 8,
    description: '酱香浓郁，下饭神器',
    method: '1.鸡腿肉500g切块焯水\n2.锅中少油炒糖色至枣红色\n3.下鸡块翻炒上色\n4.加料酒2勺、生抽3勺、老抽1勺\n5.加开水没过鸡块，小火炖20分钟\n6.大火收汁，撒葱花出锅',
    suitableTarget: ['muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 35,
    image: '',
  },
  {
    id: 'c_l_2',
    name: '番茄炒蛋',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 160,
    protein: 12,
    fat: 10,
    carbs: 8,
    description: '经典家常菜，酸甜可口',
    method: '1.番茄2个切块，鸡蛋3个打散\n2.热锅凉油，倒入蛋液炒至凝固盛出\n3.锅中再加少许油，下番茄块翻炒\n4.炒出汁水后加糖1勺、盐适量\n5.倒入炒好的鸡蛋翻炒均匀即可',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 10,
    image: '',
  },
  {
    id: 'c_l_3',
    name: '麻婆豆腐',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 200,
    protein: 15,
    fat: 12,
    carbs: 10,
    description: '麻辣鲜香，川味经典',
    method: '1.嫩豆腐1盒切块水\n2.肉末100g炒散备用\n3.锅中放豆瓣酱1勺炒出红油\n4.加蒜末、姜末炒香\n5.加水烧开，下豆腐块煮3分钟\n6.勾薄芡，撒花椒粉、葱花出锅',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 15,
    image: '',
  },
  {
    id: 'c_l_4',
    name: '清蒸鲈鱼',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 150,
    protein: 25,
    fat: 5,
    carbs: 2,
    description: '鲜嫩滑爽，高蛋白低脂',
    method: '1.鲈鱼1条处理干净，两面划刀\n2.鱼身抹盐、料酒腌制10分钟\n3.盘中铺姜片、葱段，放鱼\n4.大火蒸8-10分钟\n5.倒掉蒸出的水，铺上新葱丝、姜丝\n6.淋热油和蒸鱼豉油即可',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 15,
    image: '',
  },
  {
    id: 'c_l_5',
    name: '宫保鸡丁',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 260,
    protein: 22,
    fat: 14,
    carbs: 12,
    description: '辣而不燥，花生酥脆',
    method: '1.鸡胸肉200g切丁，加料酒、淀粉腌制\n2.花生米50g炒熟备用\n3.调汁：生抽2勺、醋1勺、糖1勺、淀粉1勺\n4.热锅爆香干辣椒、花椒\n5.下鸡丁滑炒至变色\n6.倒入料汁和花生米翻炒均匀',
    suitableTarget: ['muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 20,
    image: '',
  },
  {
    id: 'c_l_6',
    name: '鱼香肉丝',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 230,
    protein: 20,
    fat: 10,
    carbs: 14,
    description: '酸甜微辣，下饭神器',
    method: '1.里脊肉200g切丝，加料酒、淀粉腌制\n2.木耳、胡萝卜、青椒切丝\n3.调鱼香汁：生抽2勺、醋2勺、糖1勺、淀粉1勺\n4.热锅爆香葱姜蒜和豆瓣酱\n5.下肉丝滑炒至变色\n6.加蔬菜丝和料汁翻炒均匀',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 20,
    image: '',
  },
  {
    id: 'c_l_7',
    name: '回锅肉',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 300,
    protein: 22,
    fat: 18,
    carbs: 8,
    description: '川菜经典，肥而不腻',
    method: '1.五花肉300g冷水下锅煮15分钟\n2.捞出切片，蒜苗切段\n3.锅中少油炒肉片至卷曲出油\n4.加豆瓣酱1勺、甜面酱1勺炒出红油\n5.加蒜苗段翻炒断生\n6.淋少许酱油出锅',
    suitableTarget: ['muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 30,
    image: '',
  },
  {
    id: 'c_l_8',
    name: '可乐鸡翅',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 240,
    protein: 24,
    fat: 12,
    carbs: 8,
    description: '甜咸适口，老少皆宜',
    method: '1.鸡翅8个两面划刀\n2.锅中少油将鸡翅煎至两面金黄\n3.倒可乐没过鸡翅\n4.加生抽2勺、老抽1勺、姜片\n5.大火烧开转小火炖15分钟\n6.大火收汁至浓稠',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 25,
    image: '',
  },
  {
    id: 'c_l_9',
    name: '水煮牛肉',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 280,
    protein: 30,
    fat: 16,
    carbs: 6,
    description: '麻辣鲜烫，川味代表作',
    method: '1.牛肉300g切薄片，加蛋清、淀粉抓匀\n2.豆芽、莴笋焯水垫底\n3.锅中放大量干辣椒、花椒炒香\n4.加水煮开，下牛肉片煮2分钟\n5.连汤倒入蔬菜上\n6.撒蒜末、辣椒面，淋热油激发香气',
    suitableTarget: ['muscle', 'keep'],
    difficulty: 'hard',
    cookTime: 30,
    image: '',
  },
  {
    id: 'c_l_10',
    name: '糖醋排骨',
    category: 'chinese',
    mealType: 'lunch',
    calorie: 320,
    protein: 24,
    fat: 16,
    carbs: 20,
    description: '酸甜酥脆，经典下饭菜',
    method: '1.排骨400g焯水去血沫\n2.锅中多油，排骨炸至金黄捞出\n3.调糖醋汁：番茄酱3勺、醋2勺、糖2勺、生抽1勺\n4.锅中少油炒香糖醋汁\n5.下排骨翻炒裹匀酱汁\n6.撒白芝麻出锅',
    suitableTarget: ['muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 35,
    image: '',
  },

  // ========== 中餐 - 晚餐 ==========
  {
    id: 'c_d_1',
    name: '白灼西兰花',
    category: 'chinese',
    mealType: 'dinner',
    calorie: 45,
    protein: 3,
    fat: 0.5,
    carbs: 6,
    description: '清淡爽口，晚餐减脂优选',
    method: '1.西兰花掰成小朵洗净\n2.锅中烧开水，加少许盐和油\n3.下西兰花焯水2分钟\n4.捞出沥干摆盘\n5.淋少许蒸鱼豉油即可',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 5,
    image: '',
  },
  {
    id: 'c_d_2',
    name: '紫菜蛋花汤',
    category: 'chinese',
    mealType: 'dinner',
    calorie: 60,
    protein: 6,
    fat: 3,
    carbs: 4,
    description: '简单快手，暖胃舒心',
    method: '1.紫菜撕碎用温水泡开\n2.鸡蛋2个打散备用\n3.锅中加水500ml烧开\n4.放入紫菜煮1分钟\n5.缓缓倒入蛋液，用勺子轻轻搅拌\n6.加盐、香油调味即可',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 5,
    image: '',
  },
  {
    id: 'c_d_3',
    name: '冬瓜排骨汤',
    category: 'chinese',
    mealType: 'dinner',
    calorie: 120,
    protein: 10,
    fat: 6,
    carbs: 5,
    description: '清热利水，营养丰富',
    method: '1.排骨300g焯水去血沫\n2.冬瓜500g去皮切块\n3.砂锅中加水和排骨，大火烧开\n4.转小火炖40分钟\n5.加入冬瓜块再煮15分钟\n6.加盐调味，撒枸杞和葱花',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 60,
    image: '',
  },
  {
    id: 'c_d_4',
    name: '蒜蓉粉丝蒸扇贝',
    category: 'chinese',
    mealType: 'dinner',
    calorie: 90,
    protein: 14,
    fat: 3,
    carbs: 6,
    description: '鲜美嫩滑，低脂高蛋白',
    method: '1.粉丝用温水泡软铺在盘底\n2.扇贝肉洗净放在粉丝上\n3.蒜末加少许油炒香\n4.蒜蓉铺在扇贝上\n5.大火蒸5分钟\n6.淋蒸鱼豉油，撒葱花',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 10,
    image: '',
  },
  {
    id: 'c_d_5',
    name: '西红柿豆腐汤',
    category: 'chinese',
    mealType: 'dinner',
    calorie: 70,
    protein: 6,
    fat: 4,
    carbs: 5,
    description: '酸甜开胃，清爽零负担',
    method: '1.番茄2个切块，嫩豆腐1盒切块\n2.锅中少油炒软番茄出汁\n3.加水500ml烧开\n4.下豆腐块煮3分钟\n5.加盐、鸡精调味\n6.淋香油，撒葱花出锅',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 10,
    image: '',
  },
  {
    id: 'c_d_6',
    name: '凉拌黄瓜木耳',
    category: 'chinese',
    mealType: 'dinner',
    calorie: 50,
    protein: 3,
    fat: 3,
    carbs: 5,
    description: '清爽解腻，低卡首选',
    method: '1.黄瓜2根拍碎切段\n2.干木耳泡发焯水\n3.蒜末、小米椒切碎\n4.调汁：生抽2勺、醋2勺、糖1勺、香油1勺\n5.所有食材拌匀\n6.冷藏10分钟更入味',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 10,
    image: '',
  },
  {
    id: 'c_d_7',
    name: '虾仁蒸蛋',
    category: 'chinese',
    mealType: 'dinner',
    calorie: 110,
    protein: 14,
    fat: 5,
    carbs: 3,
    description: '嫩滑鲜香，营养好吸收',
    method: '1.鸡蛋3个加温水打散过滤\n2.鲜虾仁5个去虾线\n3.蛋液倒入蒸碗，盖上保鲜膜\n4.大火蒸8分钟至半凝固\n5.放入虾仁再蒸3分钟\n6.淋少许蒸鱼豉油和香油',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 15,
    image: '',
  },
  {
    id: 'c_d_8',
    name: '清炒时蔬',
    category: 'chinese',
    mealType: 'dinner',
    calorie: 60,
    protein: 3,
    fat: 4,
    carbs: 5,
    description: '简单纯粹，健康之选',
    method: '1.时令蔬菜（菜心/菠菜/空心菜）洗净\n2.蒜末备好\n3.大火热锅，倒少许油\n4.爆香蒜末\n5.下蔬菜快速翻炒1分钟\n6.加盐出锅，保持脆嫩',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 5,
    image: '',
  },

  // ========== 轻食 - 早餐 ==========
  {
    id: 'l_b_1',
    name: '牛油果吐司',
    category: 'light',
    mealType: 'breakfast',
    calorie: 250,
    protein: 8,
    fat: 14,
    carbs: 24,
    description: '健康脂肪，早餐新选择',
    method: '1.全麦吐司2片烤至微脆\n2.牛油果1个去核，果肉捣成泥\n3.加柠檬汁、黑胡椒、盐调味\n4.涂抹在吐司上\n5.可加水煮蛋切片装饰',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 5,
    image: '',
  },
  {
    id: 'l_b_2',
    name: '希腊酸奶碗',
    category: 'light',
    mealType: 'breakfast',
    calorie: 180,
    protein: 15,
    fat: 6,
    carbs: 18,
    description: '高蛋白，清爽开启一天',
    method: '1.希腊酸奶200g放入碗中\n2.加入燕麦片30g\n3.撒蓝莓、草莓等新鲜水果\n4.淋少许蜂蜜\n5.可加奇亚籽增加纤维',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 3,
    image: '',
  },
  {
    id: 'l_b_3',
    name: '蔬菜鸡蛋卷',
    category: 'light',
    mealType: 'breakfast',
    calorie: 200,
    protein: 14,
    fat: 12,
    carbs: 8,
    description: '低卡高蛋白，营养均衡',
    method: '1.鸡蛋3个打散，加盐和黑胡椒\n2.平底锅刷薄油，倒入蛋液摊平\n3.铺上菠菜碎、胡萝卜丝\n4.蛋液凝固后卷起\n5.切段装盘即可',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 8,
    image: '',
  },
  {
    id: 'l_b_4',
    name: '全麦三明治',
    category: 'light',
    mealType: 'breakfast',
    calorie: 280,
    protein: 16,
    fat: 10,
    carbs: 30,
    description: '营养均衡，便携早餐',
    method: '1.全麦面包2片\n2.煎鸡蛋1个，火腿片2片\n3.生菜叶2片，番茄2片\n4.涂抹低脂蛋黄酱\n5.层层叠放，对角切开\n6.可加芝士片增加风味',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 5,
    image: '',
  },
  {
    id: 'l_b_5',
    name: '燕麦香蕉饼',
    category: 'light',
    mealType: 'breakfast',
    calorie: 220,
    protein: 8,
    fat: 6,
    carbs: 34,
    description: '天然甜味，健康饱腹',
    method: '1.燕麦片60g用牛奶泡10分钟\n2.香蕉1根捣成泥\n3.鸡蛋1个打散加入\n4.平底锅刷薄油，舀入面糊摊成小饼\n5.小火每面煎2分钟\n6.可淋少许蜂蜜或枫糖浆',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 15,
    image: '',
  },

  // ========== 轻食 - 午餐 ==========
  {
    id: 'l_l_1',
    name: '香煎鸡胸肉沙拉',
    category: 'light',
    mealType: 'lunch',
    calorie: 220,
    protein: 32,
    fat: 8,
    carbs: 6,
    description: '增肌减脂经典搭配',
    method: '1.鸡胸肉150g用盐、黑胡椒、蒜粉腌制15分钟\n2.平底锅少油，中火煎至两面金黄熟透\n3.混合生菜、小番茄、黄瓜切片\n4.鸡胸肉切条铺在沙拉上\n5.淋油醋汁（橄榄油+柠檬汁+蜂蜜+盐）',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 20,
    image: '',
  },
  {
    id: 'l_l_2',
    name: '三文鱼藜麦碗',
    category: 'light',
    mealType: 'lunch',
    calorie: 350,
    protein: 28,
    fat: 16,
    carbs: 24,
    description: 'Omega-3丰富，超级食物',
    method: '1.三文鱼150g用柠檬汁、盐、黑胡椒腌制\n2.麦80g煮熟备用\n3.平底锅少油煎三文鱼每面3分钟\n4.碗中铺藜麦，放牛油果片、玉米粒\n5.三文鱼切块放在上面\n6.淋柠檬汁和少许橄榄油',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 20,
    image: '',
  },
  {
    id: 'l_l_3',
    name: '牛油果虾仁波奇饭',
    category: 'light',
    mealType: 'lunch',
    calorie: 380,
    protein: 25,
    fat: 18,
    carbs: 28,
    description: '夏威夷风味，营养全面',
    method: '1.糙米饭1碗煮熟\n2.虾仁150g用料酒、盐腌制后熟\n3.牛油果1个切片\n4.碗中铺糙米饭，放虾仁、牛油果、毛豆、玉米\n5.淋照烧汁或芝麻酱\n6.撒白芝麻和海苔碎',
    suitableTarget: ['muscle', 'keep'],
    difficulty: 'medium',
    cookTime: 25,
    image: '',
  },
  {
    id: 'l_l_4',
    name: '地中海式烤蔬菜',
    category: 'light',
    mealType: 'lunch',
    calorie: 180,
    protein: 6,
    fat: 10,
    carbs: 16,
    description: '意式风味，低卡高纤',
    method: '1.彩椒、西葫芦、茄子切块\n2.拌橄榄油、蒜末、迷迭香、盐\n3.烤箱200度烤20分钟\n4.可搭配菲达奶酪碎\n5.淋巴萨米克醋提味',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 25,
    image: '',
  },
  {
    id: 'l_l_5',
    name: '鸡胸肉全麦卷',
    category: 'light',
    mealType: 'lunch',
    calorie: 260,
    protein: 28,
    fat: 8,
    carbs: 22,
    description: '高蛋白低脂，健身达人最爱',
    method: '1.全麦卷饼1张\n2.鸡胸肉100g煎熟切条\n3.生菜、番茄片、黄瓜条\n4.涂低脂酸奶酱\n5.将所有食材卷入饼中\n6.斜切两段装盘',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 15,
    image: '',
  },
  {
    id: 'l_l_6',
    name: '日式味增汤配饭团',
    category: 'light',
    mealType: 'lunch',
    calorie: 300,
    protein: 12,
    fat: 6,
    carbs: 48,
    description: '日式清淡，暖胃舒服',
    method: '1.米饭1碗拌少许芝麻和盐\n2.手沾水将饭捏成三角形饭团\n3.海苔包在饭团底部\n4.味增1勺用少许热水化开\n5.豆腐切小块，海带芽泡发\n6.锅中水烧开，下豆腐和海带煮2分钟，关火入味增搅匀',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 15,
    image: '',
  },
  {
    id: 'l_l_7',
    name: '鲜虾牛油果手卷',
    category: 'light',
    mealType: 'lunch',
    calorie: 280,
    protein: 20,
    fat: 16,
    carbs: 18,
    description: '清新爽脆，日式轻食',
    method: '1.寿司海苔1张铺平\n2.醋饭60g铺在海苔上\n3.虾仁5个、牛油果片、黄瓜条\n4.挤少许是拉差辣酱\n5.从一端卷成锥形\n6.即刻享用',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 10,
    image: '',
  },

  // ========== 轻食 - 晚餐 ==========
  {
    id: 'l_d_1',
    name: '凯撒沙拉',
    category: 'light',
    mealType: 'dinner',
    calorie: 180,
    protein: 10,
    fat: 12,
    carbs: 10,
    description: '经典西式沙拉，清爽低卡',
    method: '1.罗马生菜洗净撕成小块\n2.烤面包丁：吐司切块，烤箱180度烤5分钟\n3.调凯撒酱：蛋黄+柠檬汁+蒜末+橄榄油+帕玛森芝士\n4.生菜拌上酱汁\n5.放上面包丁和芝士碎',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 10,
    image: '',
  },
  {
    id: 'l_d_2',
    name: '蒸蛋配蔬菜',
    category: 'light',
    mealType: 'dinner',
    calorie: 100,
    protein: 10,
    fat: 6,
    carbs: 4,
    description: '嫩滑如布丁，轻盈晚餐',
    method: '1.鸡蛋2个打散，加温水（蛋水比1:1.5）\n2.过滤蛋液到蒸碗中\n3.盖上保鲜膜，扎几个小孔\n4.大火蒸10-12分钟\n5.旁边配焯熟的西兰花和胡萝卜',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 15,
    image: '',
  },
  {
    id: 'l_d_3',
    name: '番茄金枪鱼沙拉',
    category: 'light',
    mealType: 'dinner',
    calorie: 160,
    protein: 22,
    fat: 6,
    carbs: 8,
    description: '高蛋白低脂，减脂晚餐首选',
    method: '1.金枪鱼罐头1罐沥干水分\n2.小番茄对半切开\n3.混合生菜、黄瓜片、洋葱丝\n4.放金枪鱼和番茄\n5.淋柠檬汁、橄榄油、盐和黑胡椒',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 5,
    image: '',
  },
  {
    id: 'l_d_4',
    name: '蘑菇蔬菜汤',
    category: 'light',
    mealType: 'dinner',
    calorie: 80,
    protein: 4,
    fat: 3,
    carbs: 10,
    description: '温暖舒适，零负担',
    method: '1.蘑菇3种（口蘑、香菇、金针菇）切片\n2.洋葱1/4个切丝\n3.锅中少油炒软洋葱\n4.加蘑菇翻炒出香\n5.加水500ml煮10分钟\n6.加盐、黑胡椒、少许奶油调味',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 15,
    image: '',
  },
  {
    id: 'l_d_5',
    name: '鸡胸肉蔬菜沙拉',
    category: 'light',
    mealType: 'dinner',
    calorie: 200,
    protein: 28,
    fat: 6,
    carbs: 8,
    description: '高蛋白低脂，增肌必备',
    method: '1.鸡胸肉150g煮熟撕成丝\n2.混合生菜、芝麻菜、苦\n3.加小番茄、黄瓜片、紫甘蓝丝\n4.调柠檬蜂蜜汁：柠檬汁+蜂蜜+橄榄油\n5.所有食材拌匀\n6.撒少许帕玛森芝士碎',
    suitableTarget: ['fat', 'muscle', 'keep'],
    difficulty: 'easy',
    cookTime: 15,
    image: '',
  },
  {
    id: 'l_d_6',
    name: '豆腐海带味噌汤',
    category: 'light',
    mealType: 'dinner',
    calorie: 70,
    protein: 6,
    fat: 3,
    carbs: 5,
    description: '日式经典，暖身轻食',
    method: '1.嫩豆腐切小块\n2.干海带芽泡发\n3.味增1大勺用少许温水化开\n4.锅中水500ml烧开，下豆腐煮2分钟\n5.关火，倒入味增汤搅匀\n6.撒葱花和海带芽',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 10,
    image: '',
  },
  {
    id: 'l_d_7',
    name: '越南春卷',
    category: 'light',
    mealType: 'dinner',
    calorie: 150,
    protein: 12,
    fat: 4,
    carbs: 18,
    description: '清爽透明，越式风情',
    method: '1.越南米纸用温水泡软\n2.虾仁煮熟对半切开\n3.米粉煮熟沥干\n4.薄荷叶、生菜、黄瓜丝备好\n5.米纸上放食材，两边折起后卷紧\n6.配鱼露或花生酱蘸食',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'medium',
    cookTime: 20,
    image: '',
  },
  {
    id: 'l_d_8',
    name: '烤南瓜麦沙拉',
    category: 'light',
    mealType: 'dinner',
    calorie: 220,
    protein: 8,
    fat: 10,
    carbs: 26,
    description: '秋冬暖沙拉，营养满分',
    method: '1.南瓜300g切块，拌橄榄油和孜然粉\n2.烤箱200度烤20分钟至软糯\n3.藜麦80g煮熟放凉\n4.混合芝麻菜、核桃碎、蔓越莓干\n5.放烤南瓜\n6.淋巴沙米克醋和橄榄油',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 30,
    image: '',
  },
  {
    id: 'l_d_9',
    name: '凉拌魔芋丝',
    category: 'light',
    mealType: 'dinner',
    calorie: 30,
    protein: 1,
    fat: 2,
    carbs: 3,
    description: '几乎零卡，减脂终极利器',
    method: '1.魔芋丝200g焯水2分钟去碱味\n2.黄瓜切丝，胡萝卜切丝\n3.蒜末、小米椒、香菜切碎\n4.调汁：生抽2勺、醋2勺、辣椒油半勺、香油少许\n5.所有食材拌匀\n6.冷藏10分钟口感更佳',
    suitableTarget: ['fat', 'keep'],
    difficulty: 'easy',
    cookTime: 10,
    image: '',
  },
];

// 按分类筛选
export function getRecipesByCategory(category: 'chinese' | 'light'): Recipe[] {
  return RECIPES.filter((r) => r.category === category);
}

export function getRecipesByMealType(mealType: 'breakfast' | 'lunch' | 'dinner'): Recipe[] {
  return RECIPES.filter((r) => r.mealType === mealType);
}

export function getRecipesByCategoryAndMeal(
  category: 'chinese' | 'light',
  mealType: 'breakfast' | 'lunch' | 'dinner'
): Recipe[] {
  return RECIPES.filter((r) => r.category === category && r.mealType === mealType);
}

export function getRecipesByTarget(target: 'fat' | 'muscle' | 'keep'): Recipe[] {
  return RECIPES.filter((r) => r.suitableTarget.includes(target));
}

// 搜索菜谱
export function searchRecipes(keyword: string): Recipe[] {
  const lower = keyword.toLowerCase();
  return RECIPES.filter(
    (r) =>
      r.name.toLowerCase().includes(lower) ||
      r.description.toLowerCase().includes(lower)
  );
}

// 获取指定日期的定制餐单
export function getRecipesByDate(date: string): Recipe[] {
  try {
    const data = localStorage.getItem('saved_meal_plans');
    if (!data) return [];
    const plans = JSON.parse(data);
    const plan = plans.find((p: { date: string }) => p.date === date);
    return plan ? plan.recipes : [];
  } catch {
    return [];
  }
}

// 删除指定日期的餐单
export function deleteMealPlanByDate(date: string): void {
  try {
    const data = localStorage.getItem('saved_meal_plans');
    if (!data) return;
    const plans = JSON.parse(data);
    const filtered = plans.filter((p: { date: string }) => p.date !== date);
    localStorage.setItem('saved_meal_plans', JSON.stringify(filtered));
  } catch {}
}
